# Mutilated beyond recognition from the example at:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  - master

strategy:
  matrix:
  #  linux:
  #    imageName: ubuntu-16.04
  #    gorootDir: /usr/local
    mac:
      imageName: macos-10.13
      gorootDir: /usr/local

pool:
  vmImage: $(imageName)

variables:
  # System.Debug: True
  GOROOT: $(gorootDir)/go
  GOPATH: $(system.defaultWorkingDirectory)/gopath
  GOBIN:  $(GOPATH)/bin
  GOGIT:  $(system.defaultWorkingDirectory)/git
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)'
  # TODO: modules should be the default in Go 1.13, so this won't be needed
  GO111MODULE: on

resources:
  repositories:
  - repository: knative-client
    type: github
    name: openshift/knative-client
    ref: refs/tags/v0.9.0
    endpoint: mvinkler

steps:
  - bash: |
      printf "Using go at: $(which go)\n"
      printf "Go version: $(go version)\n"
      printf "\n\nGo environment:\n\n"
      go env
      printf "\n\nSystem environment:\n\n"
      env
    displayName: Print Go version and environment

  - bash: |
      latestGo=$(curl "https://golang.org/VERSION?m=text")
      echo "##vso[task.setvariable variable=LATEST_GO]$latestGo"
      echo "Latest Go version: $latestGo"
    displayName: "Get latest Go version"

  - bash: |
      sudo rm -f $(which go)
      echo '##vso[task.prependpath]$(GOBIN)'
      echo '##vso[task.prependpath]$(GOROOT)/bin'
      mkdir -p '$(modulePath)'
      shopt -s extglob
      shopt -s dotglob
      mv !(gopath) '$(modulePath)'
    displayName: Remove old Go, set GOBIN/GOROOT, and move project into GOPATH

  # Install Go (this varies by platform)

  - bash: |
      wget "https://dl.google.com/go/$(LATEST_GO).linux-amd64.tar.gz"
      sudo tar -C $(gorootDir) -xzf "$(LATEST_GO).linux-amd64.tar.gz"
    condition: eq( variables['Agent.OS'], 'Linux' )
    displayName: Install Go on Linux

  - bash: |
      wget "https://dl.google.com/go/$(LATEST_GO).darwin-amd64.tar.gz"
      sudo tar -C $(gorootDir) -xzf "$(LATEST_GO).darwin-amd64.tar.gz"
    condition: eq( variables['Agent.OS'], 'Darwin' )
    displayName: Install Go on macOS

  - powershell: |
      Write-Host "Downloading Go... (please be patient, I am very slow)"
      (New-Object System.Net.WebClient).DownloadFile("https://dl.google.com/go/$(LATEST_GO).windows-amd64.zip", "$(LATEST_GO).windows-amd64.zip")
      Write-Host "Extracting Go... (I'm slow too)"
      Expand-Archive "$(LATEST_GO).windows-amd64.zip" -DestinationPath "$(gorootDir)"
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    displayName: Install Go on Windows

  # TODO: When this issue is fixed, replace with installer script:
  # https://github.com/golangci/golangci-lint/issues/472
  - script: go get -v github.com/golangci/golangci-lint/cmd/golangci-lint
    displayName: Install golangci-lint

  - bash: |
      printf "Using go at: $(which go)\n"
      printf "Go version: $(go version)\n"
      printf "\n\nGo environment:\n\n"
      go env
      printf "\n\nSystem environment:\n\n"
      env
    displayName: Print Go version and environment


  - checkout: knative-client # will checkout at $(Pipeline.Workspace)/knative-client

  - bash: |
      mkdir -p '$(GOGIT)'
      printf "Using go at: $(which go)\n"
      printf "Go version: $(go version)\n"
      printf "\n\nGo environment:\n\n"
      go env
      printf "\n\nSystem environment:\n\n"
      env
    displayName: Git

  - script: |
      go version
      if [ -f Gopkg.toml ]; then
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          dep ensure
      fi
      go build -v .
    workingDirectory: '$(modulePath)'
    displayName: 'Get dependencies, then build'